service: deals-api

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  environment:
    API_ENV: ${opt:stage, self:provider.stage}
    API_AUTH: ${env:API_AUTH}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        # Can either do by specific arn or wildcard ** Should probably not do this so insecurely **
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
    create-campus:
      handler: bin/create-campus
      events:
        - http:
            path: campuses
            method: post

    get-campuses:
      handler: bin/get-campuses
      events:
        - http:
            path: campuses
            method: get

    get-campus:
      handler: bin/get-campus
      events:
        - http:
            path: campuses/{slug}
            method: get
            request:
              parameters:
                paths:
                  slug: true

    get-locations:
      handler: bin/get-locations
      events:
        - http:
            path: campuses/{slug}/locations
            method: get
            request:
              parameters:
                paths:
                  slug: true

    get-current:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}/current
            method: get
            request:
              parameters:
                paths:
                  slug: true

    search:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}/search
            method: get
            request:
              parameters:
                paths:
                  slug: true

    create-location:
      handler: bin/create-location
      events:
          - http:
              path: campuses/{slug}/locations
              method: post
              request:
                parameters:
                  paths:
                    slug: true

    get-location:
      handler: bin/get-location
      events:
        - http:
            path: locations/{location-id}
            method: get
            request:
              parameters:
                paths:
                  location-id: true

    remove-location:
      handler: bin/remove-location
      events:
        - http:
            path: locations/{location-id}
            method: delete
            request:
              parameters:
                paths:
                  location-id: true

    get-deals:
      handler: bin/get-deals
      events:
        - http:
            path: locations/{location-id}/deals
            method: get
            request:
              parameters:
                paths:
                  location-id: true

    create-deal:
      handler: bin/create-deal
      events:
        - http:
            path: locations/{location-id}/deals
            method: post
            request:
              parameters:
                paths:
                  location-id: true

    remove-deal:
      handler: bin/remove-deal
      events:
        - http:
            path: /deals/{deal-id}
            method: delete
            request:
              parameters:
                paths:
                  deal-id: true

