service: deals-api

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  environment:
    API_ENV: ${opt:stage, self:provider.stage}
    API_AUTH: ${env:API_AUTH}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        # Can either do by specific arn or wildcard ** Should probably not do this so insecurely **
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

# part of packaging trouble can be solved with 'individually'
# https://serverless.com/framework/docs/providers/aws/guide/packaging/
package:
  individually: true
  exclude:
    - ./**


functions:
    analytics:
      handler: bin/analytics
      package:
          include:
            - ./bin/analytics
      events:
        - http:
            path: /analytics
            method: post


    sms:
      runtime: python3.7
      handler: functions/sms/handler.process
      package:
        individually: true
        exclude:
          - ./**
        include:
          - functions/sms/handler.py
        events:
          - http:
              path: /sms
              method: post

    email-processing:
      runtime: python3.7
      handler: functions/email/handler.process
      package:
        individually: true
        exclude:
          - ./**
        include:
          - functions/email/handler.py
      events:
        - s3:
            bucket: getdealsontap-update-emails
            event: s3:ObjectCreated:*

    # email-forwarding:
    #   runtime: node8.10
    #   handler: functions/email/

    create-campus:
      handler: bin/create-campus
      package:
          include:
            - ./bin/create-campus
      events:
        - http:
            path: campuses
            method: post

    get-campuses:
      handler: bin/get-campuses
      package:
          include:
            - ./bin/get-campuses
      events:
        - http:
            path: campuses
            method: get

    get-campus:
      handler: bin/get-campus
      package:
          include:
            - ./bin/get-campus
      events:
        - http:
            path: campuses/{slug}
            method: get
            request:
              parameters:
                paths:
                  slug: true

    get-locations:
      handler: bin/get-locations
      package:
          include:
            - ./bin/get-locations
      events:
        - http:
            path: campuses/{slug}/locations
            method: get
            request:
              parameters:
                paths:
                  slug: true

    get-current:
      handler: bin/not-implemented
      package:
          include:
            - ./bin/not-implemented
      events:
        - http:
            path: /{slug}/current
            method: get
            request:
              parameters:
                paths:
                  slug: true

    search:
      handler: bin/not-implemented
      package:
          include:
            - ./bin/not-implemented
      events:
        - http:
            path: /campuses/{slug}/search
            method: get
            request:
              parameters:
                paths:
                  slug: true

    create-location:
      handler: bin/create-location
      package:
          include:
            - ./bin/create-location
      events:
          - http:
              path: campuses/{slug}/locations
              method: post
              request:
                parameters:
                  paths:
                    slug: true

    get-location:
      handler: bin/get-location
      package:
          include:
            - ./bin/get-location
      events:
        - http:
            path: locations/{location-id}
            method: get
            request:
              parameters:
                paths:
                  location-id: true

    remove-location:
      handler: bin/remove-location
      package:
          include:
            - ./bin/remove-location
      events:
        - http:
            path: locations/{location-id}
            method: delete
            request:
              parameters:
                paths:
                  location-id: true

    get-deals:
      handler: bin/get-deals
      package:
          include:
            - ./bin/get-deals
      events:
        - http:
            path: locations/{location-id}/deals
            method: get
            request:
              parameters:
                paths:
                  location-id: true

    create-deal:
      handler: bin/create-deal
      package:
          include:
            - ./bin/create-deal
      events:
        - http:
            path: locations/{location-id}/deals
            method: post
            request:
              parameters:
                paths:
                  location-id: true

    remove-deal:
      handler: bin/remove-deal
      package:
          include:
            - ./bin/remove-deal
      events:
        - http:
            path: /deals/{deal-id}
            method: delete
            request:
              parameters:
                paths:
                  deal-id: true

