service: deals-api

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  environment:
    API_ENV: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        # Can either do by specific arn or wildcard ** Should probably not do this so insecurely **
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
    get-campuses:
      handler: bin/not-implemented
      events:
        - http:
            path: campuses
            method: get

    get-campus:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}
            method: get

    get-locations:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}/locations
            method: get

    get-current:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}/current
            method: get

    search:
      handler: bin/not-implemented
      events:
        - http:
            path: /{slug}/search
            method: get

    create-location:
      handler: bin/create-location
      events:
          - http:
              path: /{slug}/locations
              method: get

    get-location:
      handler: bin/not-implemented
      events:
        - http:
            path: locations/{location-id}
            method: get

    remove-location:
      handler: bin/not-implemented
      events:
        - http:
            path: locations/{location-id}
            method: delete

    get-deals:
      handler: bin/not-implemented
      events:
        - http:
            path: locations/{location-id}/deals
            method: get

    create-deal:
      handler: bin/create-deal
      events:
        - http:
            path: locations/{location-id}/deals
            method: get

    remove-deal:
      handler: bin/not-implemented
      events:
        - http:
            path: locations/{location-id}/deals/{deal-id}
            method: get
